import type { QuestionPayload } from './schemas'

/**
 * AI-driven questions are now generated dynamically based on user context.
 * This file is kept for reference but questions are no longer hardcoded.
 * 
 * The AI system will generate contextual questions based on:
 * - User profile (age, goals, health status)
 * - Previous answers in the conversation
 * - Health assessment areas (nutrition, sleep, stress, activity, etc.)
 */

// Kept for backwards compatibility - use aiNextQuestion() instead
const categories = [
  {
    topic: 'sleep',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I feel calm before bedtime',
      'I sleep at similar times most nights',
      'I do not lie awake worrying at night',
      'I sleep enough for my body',
      'My sleep helps my energy the next day',
      'I feel mentally rested after sleep',
      'I sleep through the night without many wakeups',
      'My sleep feels steady and regular',
      'I sleep well even when I have stress',
      'I keep my bedtime routine simple and calm',
      'I wake up without aches or stiffness',
      'I feel rested without using caffeine',
      'My sleep supports my health goals',
      'I do not feel sleepy during the day',
    ],
  },
  {
    topic: 'hydration',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I drink water throughout the day',
      'I feel thirsty only rarely',
      'I keep a water bottle with me',
      'I choose water over sugary drinks',
      'I drink water before my meals',
      'I drink water after exercise',
      'I feel better after drinking water',
      'I drink at least 6 glasses of water daily',
      'I know when my body needs more water',
      'I avoid drinking too much soda',
      'I feel hydrated during work or study',
      'I do not forget to drink water',
      'I replace salty snacks with water well',
      'I use water to refresh between meals',
      'I enjoy drinking plain or light flavored water',
    ],
  },
  {
    topic: 'energy',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I have steady energy during the day',
      'I do not feel tired after lunch',
      'I feel alert in the afternoon',
      'I can focus without needing extra sugar',
      'My energy does not crash suddenly',
      'I feel strong when I move my body',
      'I can finish my tasks without fatigue',
      'I feel ready to be active each day',
      'I wake up with enough energy',
      'I handle a busy day without low energy',
      'I do not depend on coffee to function',
      'I feel balanced energy before bed',
      'I eat foods that help keep my energy even',
      'I have enough energy for light exercise',
      'I do not feel drained after work',
      'I feel energized after a healthy meal',
      'I avoid heavy meals that make me sleepy',
      'I feel motivated by my energy levels',
      'I do not need naps to get through the day',
      'I feel clear-headed and awake most of the day',
    ],
  },
  {
    topic: 'stress',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I feel calm and manage stress well',
      'I take deep breaths when I feel tense',
      'I can relax after a busy moment',
      'I keep stress from affecting my meals',
      'I take breaks when I need them',
      'I do not feel overwhelmed by small tasks',
      'I use simple methods to calm myself',
      'I feel peaceful at least once a day',
      'I can let go of stress before bed',
      'I handle pressure without feeling lost',
      'I do not let stress ruin my eating habits',
      'I feel able to slow down when I need it',
      'I have ways to clear my mind',
      'I feel patient with myself daily',
      'I face challenges without too much worry',
    ],
  },
  {
    topic: 'mindset',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I feel motivated to take care of my health',
      'I believe I can improve my habits',
      'I stay positive about healthy changes',
      'I focus on what I can do today',
      'I feel that health is worth my effort',
      'I reward myself for small wins',
      'I notice progress in my habits',
      'I feel confident with my choices',
      'I keep learning about healthy living',
      'I stay calm when a plan does not go perfect',
      'I trust myself to make better food choices',
      'I believe I can build a stronger routine',
      'I see healthy food as a good choice',
      'I feel ready to try new healthy habits',
      'I keep my focus on long-term results',
      'I feel hopeful about my health future',
      'I can move forward after a setback',
      'I stay patient with my health journey',
      'I feel driven by simple progress',
      'I enjoy taking care of my body',
    ],
  },
  {
    topic: 'motivation',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I set small health goals for the week',
      'I track one habit I want to build',
      'I feel proud when I reach a small goal',
      'I plan my meals before the day starts',
      'I keep a note of my health steps',
      'I stay committed to my simple routine',
      'I choose one healthy action daily',
      'I try again if I miss my plan',
      'I feel motivated by progress, not perfection',
      'I celebrate small healthy choices',
      'I keep moving forward with healthy habits',
      'I act on my health plan most days',
      'I use my goals to stay on track',
      'I feel encouraged when I eat well',
      'I remind myself why health matters',
    ],
  },
  {
    topic: 'food_choices',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I choose vegetables and lean protein',
      'I pick whole grains when I can',
      'I include fruit in my snacks',
      'I limit fried and heavy foods',
      'I add greens to at least one meal',
      'I choose grilled or baked options',
      'I add healthy fats like nuts or avocado',
      'I avoid too much sugar in drinks',
      'I prefer cooked meals over fast food',
      'I include a source of protein in each meal',
      'I eat enough fiber from food',
      'I choose foods that keep me full longer',
      'I avoid large portions of processed food',
      'I serve smaller helpings when I feel full',
      'I opt for a salad or bowl more often',
      'I choose soups or stews on colder days',
      'I keep my plate colorful with veggies',
      'I select meals that match my energy needs',
      'I feel good about what I eat most meals',
      'I eat with purpose instead of eating by habit',
    ],
  },
  {
    topic: 'cravings',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I control cravings for sweets',
      'I avoid eating junk food when bored',
      'I choose a healthy snack instead of candy',
      'I stop eating when I feel satisfied',
      'I plan snacks so I do not overeat',
      'I do not eat just because food is available',
      'I enjoy a small treat without overdoing it',
      'I can wait before I eat a craving snack',
      'I drink water before I reach for a snack',
      'I keep healthy foods ready when I am hungry',
      'I notice true hunger before eating',
      'I avoid mindless snacking in front of screens',
      'I feel in control of my food urges',
      'I choose balanced snacks over sweets',
      'I stop cravings with a healthy choice',
    ],
  },
  {
    topic: 'body_awareness',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I notice how food affects my mood',
      'I can tell when I am truly hungry',
      'I stop eating when my body feels full',
      'I feel aware of my stomach signals',
      'I mind my bodyG��s needs after exercise',
      'I know when I need rest after a busy day',
      'I listen to my body before choosing food',
      'I notice when food makes me feel heavy',
      'I feel connected to my bodyG��s energy level',
      'I choose meals that help my body recover',
      'I can sense when I need more fluids',
      'I notice if a meal was too large for me',
      'I feel my body respond positively to healthy food',
      'I pick foods that match my activity level',
      'I feel safe listening to my body cues',
    ],
  },
  {
    topic: 'exercise',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I move my body regularly each week',
      'I enjoy a walk or light exercise',
      'I stretch my body often',
      'I choose stairs instead of lifts when I can',
      'I feel stronger when I am active',
      'I make time for some physical activity',
      'I feel better after moving my body',
      'I do not sit for too many hours at once',
      'I include activity in my daily routine',
      'I keep my muscles active with simple moves',
      'I use short breaks to stand and stretch',
      'I feel energized after a short workout',
      'I enjoy light movement after meals',
      'I do not avoid physical activity completely',
      'I feel motivated to stay active most days',
      'I build activity into my day easily',
      'I feel my body recover well after exercise',
      'I keep a gentle exercise routine going',
      'I find simple ways to be active',
      'I feel good about moving each week',
    ],
  },
  {
    topic: 'support',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I have support for healthy changes',
      'I can talk to someone about my goals',
      'I feel encouraged by someone I trust',
      'I get helpful advice when I need it',
      'I have someone who checks in on me',
      'I share healthy meals with others',
      'I feel less stressed when I ask for help',
      'I can reach out when I feel stuck',
      'I feel supported by family or friends',
      'I feel more confident with support',
      'I enjoy the healthy company of others',
      'I can find support when I want to improve',
      'I have help to keep my routine on track',
      'I feel safe asking for food advice',
      'I feel supported in my health journey',
    ],
  },
  {
    topic: 'mental_health',
    options: ['Never', 'Sometimes', 'Often', 'Always'],
    statements: [
      'I feel mentally clear and balanced',
      'I can calm my mind when I feel worried',
      'I feel patient with myself each day',
      'I handle changes without too much stress',
      'I feel emotionally steady most days',
      'I take quiet time for my mind',
      'I feel connected to my inner calm',
      'I do not let negative thoughts control me',
      'I feel hopeful even when things change',
      'I take care of my mental energy',
      'I feel stronger mentally after healthy habits',
      'I know when I need a mental rest',
      'I feel determined and calm together',
      'I can notice and move past a bad mood',
      'I feel stable in my mind and body',
    ],
  },
]

export const HEALTH_MINDSET_QUESTIONS: QuestionPayload[] = categories.flatMap((category) =>
  category.statements.map((statement) => ({
    question: statement,
    topic: category.topic,
    options: category.options,
    done: false,
  }))
)
